CREATE TABLE IF NOT EXISTS persons(
    person_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_fullname VARCHAR(100) NOT NULL,
    person_age INT NOT NULL,
    person_email VARCHAR(100) NOT NULL UNIQUE,
    person_username VARCHAR(100) NOT NULL UNIQUE,
    person_password VARCHAR(200) NOT NULL);

CREATE TABLE IF NOT EXISTS tasks (
    task_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_name VARCHAR(200) NOT NULL,
    task_body VARCHAR(2000) NOT NULL,
    task_status VARCHAR(50) NOT NULL,
    task_priority VARCHAR(50) NOT NULL,
    task_creation_date DATE NOT NULL,
    task_edit_date TIMESTAMP NOT NULL,
    task_deadline DATE NOT NULL,
    task_creator_id INT REFERENCES persons(person_id),
    task_executor_id INT REFERENCES persons(person_id));

CREATE TABLE IF NOT EXISTS person_roles(
    person_role_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id INT REFERENCES persons(person_id),
    role_id INT REFERENCES roles(role_id));

CREATE TABLE IF NOT EXISTS roles(
    role_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name VARCHAR(100) NOT NULL);

INSERT INTO persons (person_name, person_age, person_email, person_username, person_password)
VALUES ('User User User',20,'user@mail.ru','user','$2y$10$I3qmVrRUUsxhAsa6gXuOZOugYDtcYO9HoCHyf5qcFth6.kBVPancC');

INSERT INTO persons (person_name, person_age, person_email, person_username, person_password)
VALUES('Admin Admin Admin',20,'admin@mail.ru','admin','$2y$10$40o6KslQwd6EC0CPSjJM2OzxPvoKfOckBbCdEz2Oq4Skh/j.NpWRa');

INSERT INTO taskstable (task_name, task_creation_date, task_body, task_status, task_priority, task_edit_date, task_deadline, creator_id, executor_id)
VALUES ('test1', 2023-01-01,'test1','OPENED', 'HIGH',2023-01-02,2023-01-05,1,2);

INSERT INTO roles (role_name) VALUES ('ROLE_USER');
INSERT INTO roles (role_name) VALUES ('ROLE_ADMIN');

INSERT INTO person_roles (person_id, role_id) VALUES (1,1);
INSERT INTO person_roles (person_id, role_id) VALUES (2,2);
